CREATE TABLE CUSTOMER_REWARDS(
    ID BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    INVOICE_ID BIGINT NOT NULL,
    INVOICE_DATE DATE,
    INVOICE_AMOUNT DOUBLE,
    REWARDS_POINT DOUBLE,
    PRIMARY KEY (ID)
);